#!/bin/zsh

SIM_DIR="$HOME/Library/Application Support/iPhone Simulator"
SIM_DIR6="$HOME/Library/Developer/CoreSimulator/Devices"
SEARCH_TERM="$1"

read_plist_key() {
    PLIST="$1"
    KEY="$2"
    /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST"
}

dirnameN() {
    dirpath=$1
    num=$2
    for (( i = 0; i < $num; i++ )); do
        dirpath="$(dirname $dirpath)"
    done
    echo $dirpath
}

find_device_name() {
    device_path="$1"
    device_name="Unknown"
    if [[ "${device_path##$SIM_DIR6}" != $device_path ]]; then
        device_path=$(dirnameN "$device_path" 3)
        # catches iOS 8 sim apps which are nested further
        if [[ $(basename $device_path) == "Containers" ]]; then
            device_path=$(dirnameN "$device_path" 2)
        fi
        device_path="$device_path/device.plist"
        if [[ -e $device_path ]]; then
            # seems kinda gross, probably better way to parse this out in shell
            device_version=$(read_plist_key "$device_path" "runtime")
            device_version=("${(s/./)device_version}")
            device_version=$device_version[-1]
            device_version=("${(s/-/)device_version}")
            device_version="$device_version[-3] $device_version[-2].$device_version[-1]"
            device_name="$(read_plist_key "$device_path" "name") - $device_version"
        fi
    else
        device_path=$(dirnameN "$device_path" 2)
        device_name=$(basename "$device_path")
    fi
    echo $device_name
}

find_items() {
    SEARCH_DIR="$1"
    find "$SEARCH_DIR" -name "*.app" -type d | while read APP_PATH; do
    INFO_PLIST="$APP_PATH/Info.plist"
    APP_NAME="$(read_plist_key $INFO_PLIST CFBundleDisplayName)"
    if [ -z "$APP_NAME" ]; then
        APP_NAME="$(read_plist_key $INFO_PLIST CFBundleName)"
    fi
    if $(echo "$APP_NAME" | grep --quiet --ignore-case "$SEARCH_TERM"); then
        DIR_NAME="$(dirname $APP_PATH)"
        device_name=$(find_device_name "$DIR_NAME")
        echo "<item arg=\"$DIR_NAME\"><title>$APP_NAME ($device_name)</title><subtitle>$APP_PATH</subtitle></item>"
    fi
done
}

# See http://www.alfredforum.com/topic/5-generating-feedback-in-workflows/
# for the XML output format Alfred expects
echo '<?xml version="1.0"?>'
echo '<items>'
find_items $SIM_DIR
find_items $SIM_DIR6
echo '</items>'
